version: '3.8'

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["dotnet", "run", "--project", "StudyTracker.csproj"]
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=server=mariadb;port=3306;database=studytrackerdb;user=root;password=mypassword
    depends_on:
      - mariadb

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: studytrackerdb
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
