name: CI Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner + ReportGenerator
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-reportgenerator-globaltool
        shell: bash

      - name: Add tool path to environment
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Clean old test results
        run: rm -rf tests/UnitTests/TestResults

      - name: Restore dependencies
        run: dotnet restore StudyTrackers.sln

      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin \
            /k:"StudyTracker" \
            /d:sonar.host.url="http://sonarqube.setgo.dk:9000" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml"

      - name: Build
        run: dotnet build StudyTrackers.sln --no-restore

      - name: Run tests with code coverage
        run: dotnet test tests/UnitTests/UnitTests.csproj --collect:"XPlat Code Coverage"

      - name: Generate coverage report
        run: |
          reportgenerator \
            -reports:"tests/UnitTests/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"Cobertura"

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
