name: CI Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore StudyTrackers.sln

      - name: Build solution
        run: dotnet build StudyTrackers.sln --no-restore

      - name: Run tests with coverage
        run: dotnet test tests/UnitTests/UnitTests.csproj --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator \
            -reports:"tests/UnitTests/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"Cobertura"

      - name: Install sonar-scanner
        run: npm install -g sonar-scanner

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=StudyTracker \
            -Dsonar.host.url=http://sonarqube.setgo.dk:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.cs.opencover.reportsPaths=coverage-report/Cobertura.xml \
            -Dsonar.sources=backend \
            -Dsonar.language=cs \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.*,frontend/**
