name: CI Build & Test

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Create tool manifest (if needed)
        run: dotnet new tool-manifest --force

      - name: Install SonarScanner & ReportGenerator
        run: |
          dotnet tool install dotnet-sonarscanner
          dotnet tool install dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore StudyTrackers.sln

      - name: Start SonarQube analysis
        run: |
          dotnet tool run dotnet-sonarscanner begin \
            /k:"StudyTracker" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="coverage-report/Cobertura.xml"

      - name: Build solution
        run: dotnet build StudyTrackers.sln --no-restore

      - name: Run tests with coverage
        run: dotnet test tests/UnitTests/UnitTests.csproj --collect:"XPlat Code Coverage"

      - name: Generate coverage report
        run: |
          dotnet tool run reportgenerator \
            -reports:"tests/UnitTests/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:"Cobertura"

      - name: End SonarQube analysis
        run: dotnet tool run dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Setup Node.js for Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Start preview server
        run: |
          cd frontend
          nohup npm run preview -- --port 5179 &
        shell: bash

      - name: Wait for frontend to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          sleep 5
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:5179

      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test
