name: CI Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET tools (SonarScanner & ReportGenerator)
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore StudyTrackers.sln

      - name: Start SonarQube analysis
        run: |
          dotnet tool run dotnet-sonarscanner begin \
            /k:"StudyTracker" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="http://sonarqube.setgo.dk:9000" \
            /d:sonar.cs.opencover.reportsPaths="coverage/Cobertura.xml"

      - name: Build solution
        run: dotnet build StudyTrackers.sln --no-restore

      - name: Run tests with coverage
        run: dotnet test tests/UnitTests/UnitTests.csproj --collect:"XPlat Code Coverage"

      - name: Generate coverage report
        run: |
          dotnet tool run reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"coverage" \
            -reporttypes:"Cobertura"

      - name: End SonarQube analysis
        run: dotnet tool run dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
