
name: CI Build & Sonar

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarQube analysis
        run: dotnet sonarscanner begin /k:"StudyTracker" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="http://sonarqube.setgo.dk:9000"
        env:
          PATH: ${{ runner.tool_cache }}/dotnet/tools:$PATH

      - name: Build
        run: dotnet build --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-build --logger trx

      - name: Run Mutation Tests
        run: |
          dotnet tool restore
          dotnet stryker --project tests/UnitTests/UnitTests.csproj

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          PATH: ${{ runner.tool_cache }}/dotnet/tools:$PATH
